### ISSUE TITLE
let people choose domain-prefix by themselves

### ISSUE THREAD

**Issue by bigmouse0001** [aokellermann/nexus-now#1]
hi developers, may I ask you to let people choose domain-prefix by themselves ?

just like Scihub X Now

![image](https://github.com/aokellermann/nexus-now/assets/119995454/ed5faa50-e12b-4ee5-a86d-58ac92fd2fce)

and maybe it would be better to let people manage url prefixes by themselves, then they could be able to add urls such as：

- https://standard--template--construct-org.ipns.dweb.link/#/nexus_science/doi:
- https://standard--template--construct-org.ipns.dweb.link/#/nexus_books/cid:
- https://zh.annas-archive.org/doi
- https://zh.annas-archive.org/md5
- https://sci-hub.se/

 thanks~

**Comment by aokellermann** [comment]
I don't have plans to support anything besides STC in this extension. As for `nexus_books` by CID, I don't see a compelling use case.

**Comment by bigmouse0001** [comment]
Thanks for replying, however, you don't see any useful case, then you imagine it's nonexistent. Maybe it's better to expand your perception besides STC. 

And I want to say, the Scihub X Now have already provide a function the same as this extension, and support more case. (I have already known it's function, but given the narrow tolerance of the STC Admin who has always been as opposed to anything besides STC, so I did not promote this approach in Nexus and any channel.)

So maybe your extension aimed to support STC is not something unique, but a repetitive work.

**Comment by aokellermann** [comment]
I am working on integration with nexus using summa, which is not something that scihub x now will support.

I'm not against sites other than STC, they are not within the scope of this extension.

**Comment by bigmouse0001** [comment]
Well, anyway, happy to see this extension will be used by many people, its useful. Thanks your work again.
