### ISSUE TITLE
Not found, yet found in telegram bot

### ISSUE THREAD

**Issue by huachuman** [aokellermann/nexus-now#4]
Every time I use NexusNow it never finds the file. Yet when I use the bot, it finds it basically every time.

**Comment by aokellermann** [comment]
See https://github.com/aokellermann/zotero-nexus/issues/3

**Comment by aokellermann** [comment]
Newest version should greatly improve PDF availability, and it should improve over time as Nexus developers add more replication.

**Comment by huachuman** [comment]
Oh great! Any chance of implementing that change to the zotero plugin?

**Comment by aokellermann** [comment]
> Oh great! Any chance of implementing that change to the zotero plugin?

Yes, I hope to find some time in the next week.
